r"""
Linear family of coordinates on a veering triangulation
"""
# ****************************************************************************
#  This file is part of veerer
#
#       Copyright (C) 2023 Vincent Delecroix
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
# ****************************************************************************

from array import array
from copy import copy
import collections
import itertools
import numbers
from random import choice, shuffle

from sage.structure.richcmp import op_LT, op_LE, op_EQ, op_NE, op_GT, op_GE, rich_to_bool
from sage.structure.element import get_coercion_model, Matrix
from sage.structure.richcmp import op_EQ, rich_to_bool
from sage.rings.integer_ring import ZZ
from sage.rings.rational_field import QQ
from sage.matrix.constructor import matrix
from sage.modules.free_module import FreeModule
from sage.geometry.polyhedron.constructor import Polyhedron
from sage.arith.misc import gcd
from sage.categories.number_fields import NumberFields

from .constants import VERTICAL, HORIZONTAL, BLUE, RED
from .constellation import Constellation
from .permutation import perm_init, perm_cycle_string, perm_cycles, perm_check, perm_conjugate, perm_on_list, perm_on_edge_list, perm_relabel_on_edges
from .polyhedron import LinearExpressions, ConstraintSystem
from .polyhedron.linear_expression import LinearConstraint
from .strebel_graph import StrebelGraph
from .veering_triangulation import VeeringTriangulation

cm = get_coercion_model()
_NumberFields = NumberFields()


def subspace_are_equal(subspace1, subspace2, check=True):
    r"""
    Test whether the subspaces generated by the rows of ``subspace1`` and
    ``subspace2`` are equal.

    INPUT:

    - ``subspace1``, ``subspace2`` -- full rank matrices with the same number
      of columns

    - ``check`` -- boolean (default ``True``)

    EXAMPLES::

        sage: from veerer.linear_family import subspace_are_equal  # random output due to deprecation warnings from realalg

        sage: m1 = random_matrix(ZZ, 3, 5)
        sage: m2 = copy(m1)
        sage: m2.add_multiple_of_row(0, 1, -2)
        sage: m2.add_multiple_of_row(0, 2, 1)
        sage: m2.add_multiple_of_row(1, 2, 1)
        sage: subspace_are_equal(m1, m2)
        True

        sage: m1 = matrix(ZZ, [[1, 1, 0]])
        sage: m2 = matrix(ZZ, [[1, 1, -1]])
        sage: subspace_are_equal(m1, m2)
        False
    """
    if check:
        if subspace1.ncols() != subspace2.ncols():
            raise ValueError('subspace1 and subspace2 of different ambient dimensions')
        if subspace1.rank() != subspace1.nrows():
            raise ValueError('subspace1 not full rank')
        if subspace2.rank() != subspace2.nrows():
            raise ValueErrror('subspace2 not full rank')

    n = subspace1.nrows()
    if n != subspace2.nrows():
        return False

    base_ring = cm.common_parent(subspace1.base_ring(), subspace2.base_ring())
    mat = matrix(base_ring, n + 1, subspace1.ncols())
    mat[:n] = subspace1
    for v in subspace2.rows():
        mat[n] = v
        r = mat.rank()
        if r < n:
            raise RuntimeError('matrices where expected to be full rank')
        if r > n:
            return False
    return True


def subspace_cmp(subspace1, subspace2, check=True):
    if check:
        if subspace1.ncols() != subspace2.ncols():
            raise ValueError('subspace1 and subspace2 of different ambient dimensions')
        if subspace1.rank() != subspace1.nrows():
            raise ValueError('subspace1 not full rank')
        if subspace2.rank() != subspace2.nrows():
            raise ValueErrror('subspace2 not full rank')

    n = subspace1.nrows()
    if n != subspace2.nrows():
        return False

    base_ring = cm.common_parent(subspace1.base_ring(), subspace2.base_ring())
    # subspace1 = subspace1.echelon_form()
    # subspace2 = subspace2.echelon_form()
    for r1, r2 in zip(subspace1, subspace2):
        c = (r1 > r2) - (r1 < r2)
        if c:
            return c
    return 0


def matrix_permutation(mat, perm):
    r"""
    Permute in place the columns of ``mat`` according to the permutation ``perm``

    EXAMPLES::

        sage: from array import array
        sage: from veerer.linear_family import matrix_permutation

        sage: p = array('i', [2, 0, 1])
        sage: m = matrix([[0, 1, 2]])
        sage: matrix_permutation(m, p)
        sage: print(m)
        [1 2 0]
    """
    m = mat.ncols()
    for c in perm_cycles(perm, False, m):
        for i in range(1, len(c)):
            mat.swap_columns(c[0], c[i])


class LinearFamily:
    r"""
    Abstract class to handle linear coordinates on either veering triangulation
    or Strebel graph.

    The subspace is given by generators.
    """
    def _constellation_class_init(self):
        bases = self.__class__.__bases__
        if len(bases) != 2 or bases[0] != LinearFamily:
            raise ValueError
        self._constellation_class = bases[1]

    def __init__(self, *args, mutable=False, check=True):
        self._constellation_class_init()

        if len(args) < 2:
            raise ValueError('require at least two arguments')
        constellation_args = args[:-1]
        subspace = args[-1]
        self._constellation_class.__init__(self, *constellation_args, mutable=mutable, check=False)

        if not isinstance(subspace, Matrix):
            subspace = matrix(subspace)

        self._subspace = subspace
        self._subspace.echelonize()
        if not mutable:
            self._subspace.set_immutable()

        if check:
            self._check(ValueError)

    def _check(self, error=ValueError):
        self._constellation_class._check(self, error)
        subspace = self._subspace
        if subspace.ncols() != self.num_edges():
            raise error('subspace matrix has wrong dimension')
        if subspace.rank() != subspace.nrows():
            raise error('subspace matrix is not of full rank')
        if subspace != subspace.echelon_form():
            raise error('subspace not in echelon form')
        if self._mutable != self._subspace.is_mutable():
            raise error('incoherent mutability states')

    def __str__(self):
        r"""
        Return a string representation.

        TESTS::

            sage: from veerer import *
            sage: vt = VeeringTriangulation("(0,1,2)(~0,~1,~2)", [RED, RED, BLUE])
            sage: str(vt.as_linear_family())
            'VeeringTriangulationLinearFamily("(0,1,2)(~0,~1,~2)", "RRB", [(1, 0, -1), (0, 1, 1)])'
        """
        cls_name = self._constellation_class.__name__
        s = str(self._constellation_class.__str__(self))
        i = s.find('(')
        return s[:i] + 'LinearFamily' + s[i:-1] + ', ' + str(self._subspace.rows()) + ')'

    def __repr__(self):
        return str(self)

    def __getstate__(self):
        R = self.base_ring()
        # NOTE: here we know that all entries have the same parent
        if R is ZZ:
            entries = list(map(int, self._subspace.list()))
        elif R is QQ:
            entries = []
            for x in self._subspace.list():
                entries.append(int(x.numerator()))
                entries.append(int(x.denominator()))
        elif _NumberFields is not None and R in _NumberFields:
            entries = []
            for x in self._subspace.list():
                v = x.vector()
                d = v.denominator()
                entries.extend(int(x) for x in (v * d))
                entries.append(int(d))
        else:
            entries = self._subspace.list()
        return self._constellation_class.__getstate__(self), R, entries

    def __setstate__(self, arg):
        r"""
        TESTS:

        An example over ZZ::

            sage: from veerer import VeeringTriangulation
            sage: vt = VeeringTriangulation("(0,1,2)(~0,~1,~2)", "RRB")
            sage: lf = vt.as_linear_family()
            sage: lf2 = loads(dumps(lf))  # indirect doctest
            sage: assert lf == lf2
            sage: lf2._check()

        An example over number fields::

            sage: from veerer.linear_family import VeeringTriangulationLinearFamilies
            sage: lf = VeeringTriangulationLinearFamilies.triangle_3_4_13_unfolding_orbit_closure()
            sage: lf2 = loads(dumps(lf))  # indirect doctest
            sage: assert lf == lf2
            sage: lf2._check()
        """
        self._constellation_class_init()
        a, R, raw_entries = arg
        self._constellation_class.__setstate__(self, a)

        if R is ZZ:
            entries = [ZZ(x) for x in raw_entries]
        elif R is QQ:
            entries = []
            for i in range(0, len(raw_entries), 2):
                entries.append(QQ((raw_entries[i], raw_entries[i + 1])))
        elif _NumberFields is not None and R in _NumberFields:
            entries = []
            d = R.degree()
            for i in range(0, len(raw_entries), d + 1):
                v = tuple(x / raw_entries[i + d] for x in raw_entries[i:i + d])
                entries.append(R(v))
        else:
            entries = raw_entries
        self._subspace = matrix(R, len(entries) // self.num_edges(), self.num_edges(), entries)
        if not self._mutable:
            self._subspace.set_immutable()

    def constellation(self, mutable=False):
        r"""
        Return the underlying combinatorial veering triangulation or Strebel graph.

        EXAMPLES::

            sage: from veerer import VeeringTriangulation, StrebelGraph

            sage: vt = VeeringTriangulation("(0,1,2)(~0,~1,~2)", "RRB")
            sage: vt.as_linear_family().constellation() == vt
            True

            sage: sg = StrebelGraph("(0,1:1,2,~1,~0,~2)")
            sage: sg.as_linear_family().constellation() == sg
            True
        """
        return Constellation.copy(self, mutable, cls=self._constellation_class)

    def copy(self, mutable=None, cls=None):
        r"""
        Return a copy of this linear family.

        EXAMPLES::

            sage: from veerer import *
            sage: fp = "(0,1,2)(~0,~4,~2)(3,4,5)(~3,~1,~5)"
            sage: cols = "BRRBRR"
            sage: f = VeeringTriangulation(fp, cols).as_linear_family(mutable=False)
            sage: f
            VeeringTriangulationLinearFamily("(0,1,2)(~0,~4,~2)(~1,~5,~3)(3,4,5)", "BRRBRR", [(1, 0, 1, 0, 0, 0), (0, 1, 1, 0, 1, 1), (0, 0, 0, 1, 0, 1)])
            sage: f2 = f.copy(mutable=True)
            sage: f2
            VeeringTriangulationLinearFamily("(0,1,2)(~0,~4,~2)(~1,~5,~3)(3,4,5)", "BRRBRR", [(1, 0, 1, 0, 0, 0), (0, 1, 1, 0, 1, 1), (0, 0, 0, 1, 0, 1)])
            sage: f2._check()
            sage: f2._mutable
            True
        """
        if mutable is None:
            mutable = self._mutable

        if cls is None:
            cls = self.__class__

        if cls is self.__class__ and (not self._mutable and not mutable):
            # avoid copies of immutable objects
            return self

        if cls is not self.__class__:
            return super().copy(mutable, cls)

        L = self._constellation_class.copy(self, mutable=True, cls=self.__class__)
        L._constellation_class = self._constellation_class
        L._subspace = copy(self._subspace)
        if not mutable:
            L._subspace.set_immutable()
        return L

    def base_ring(self):
        r"""
        Return the underlying base ring of the linear family.
        """
        return self._subspace.base_ring()

    def set_immutable(self):
        self._constellation_class.set_immutable(self)
        self._subspace.set_immutable()

    def __hash__(self):
        r"""
        TESTS::

            sage: from veerer import VeeringTriangulation
            sage: vt = VeeringTriangulation("(0,1,2)(~0,~1,~2)", "RRB")
            sage: h = hash(vt.as_linear_family())
        """
        if self._mutable:
            raise ValueError('mutable veering triangulation linear family not hashable')

        x = self._constellation_class.__hash__(self)
        x = ((x ^ hash(self._subspace) * 2147483693)) + 82520 + self._ne + self._ne

        return x

    def __eq__(self, other):
        r"""
        TESTS::

            sage: from veerer import *
            sage: vt, s, t = VeeringTriangulations.L_shaped_surface(1,1,1,1)
            sage: s = vector(QQ, s)
            sage: t = vector(QQ, t)
            sage: f1 = VeeringTriangulationLinearFamily(vt, [s, t])
            sage: f2 = VeeringTriangulationLinearFamily(vt, [s + 2*t, -s - t])
            sage: f1 == f2
            True
            sage: from veerer import *
            sage: vt2, s2, t2 = VeeringTriangulations.L_shaped_surface(1,2,1,3)
            sage: f3 = VeeringTriangulationLinearFamily(vt2, [s2, t2])
            sage: f1 == f3
            False
            sage: vt3 = VeeringTriangulation("(0,1,2)(~0,~1,~2)", [RED, RED, BLUE])
            sage: vt3 == vt3.as_linear_family()
            True
            sage: vt3.as_linear_family() == vt3
            True
            sage: vt3.as_linear_family() == f1
            False
            sage: f1 == vt3.as_linear_family()
            False
        """
        if type(self) is type(other):
            return self._constellation_class.__eq__(self, other) and self._subspace == other._subspace

        if isinstance(self, LinearFamily):
            if self._constellation_class.__ne__(self, other):
                return False
            elif isinstance(other, LinearFamily):
                return False
            else:
                # self is a linear family while other is a constellation
                return self._constellation_class.__eq__(self, other) and self.dimension() == other.dimension()

        elif isinstance(other, LinearFamily):
            if other._constellation_class.__ne__(self, other):
                return False
            elif type(self) is other._constellation_class:
                # one of self or other is a VeeringTriangulation
                return other._constellation_class.__eq__(other, self) and self.dimension() == other.dimension()
            else:
                return False

    def __ne__(self, other):
        r"""
        TESTS::

            sage: from veerer import *
            sage: vt, s, t = VeeringTriangulations.L_shaped_surface(1,1,1,1)
            sage: s = vector(QQ, s)
            sage: t = vector(QQ, t)
            sage: f1 = VeeringTriangulationLinearFamily(vt, [s, t])
            sage: f2 = VeeringTriangulationLinearFamily(vt, [s + 2*t, -s - t])
            sage: f1 != f2
            False
            sage: from veerer import *
            sage: vt2, s2, t2 = VeeringTriangulations.L_shaped_surface(1,2,1,3)
            sage: f3 = VeeringTriangulationLinearFamily(vt2, [s2, t2])
            sage: f1 != f3
            True

            sage: vt1 = VeeringTriangulation("(0,1,2)(~0,~1,~2)", [RED, RED, BLUE])
            sage: vt2 = VeeringTriangulation("(0,1,2)(~0,~1,~2)", [RED, BLUE, BLUE])
            sage: vt1.as_linear_family() != f1
            True
            sage: vt1 != vt1.as_linear_family()
            False
            sage: vt1.as_linear_family() != vt1
            False
            sage: vt1 != vt2.as_linear_family()
            True
            sage: vt2.as_linear_family() != vt1
            True
        """
        if type(self) is type(other):
            return self._constellation_class.__ne__(self, other) or self._subspace != other._subspace

        if isinstance(self, LinearFamily):
            if self._constellation_class.__ne__(self, other):
                return True
            elif isinstance(other, LinearFamily):
                return True
            else:
                # self is a linear family while other is a constellation
                return self._constellation_class.__ne__(self, other) or self.dimension() != other.dimension()

        elif isinstance(other, LinearFamily):
            if other._constellation_class.__ne__(self, other):
                return True
            elif type(self) is other._constellation_class:
                # one of self or other is a VeeringTriangulation
                return other._constellation_class.__ne__(other, self) or self.dimension() != other.dimension()
            else:
                return True

    def _richcmp_(self, other, op):
        r"""
        TESTS::

            sage: from veerer import VeeringTriangulation, VeeringTriangulationLinearFamily
            sage: f = VeeringTriangulationLinearFamily("(0:1)(~0:1,1:1,2:2)(~1:1,~2:2,3:1)(~3:1)", "RRBR", [(1, 0, 0, 1), (0, 1, 0, 0), (0, 0, 1, 0)])
            sage: f == min(x for x in f.delaunay_strebel_graph()._vertices if isinstance(x, VeeringTriangulation))
            True

            sage: f0 = VeeringTriangulationLinearFamily("(0:1)(~0:1,1:1,2:1)(~1:1,~2:1,3:1)(~3:1)", "RRBR", [(1, 0, 0, 1), (0, 1, 0, 0), (0, 0, 1, 0)])
            sage: f1 = VeeringTriangulationLinearFamily("(0:1)(~0:1,1:1,2:1)(~1:1,~2:1,3:1)(~3:1)", "BRRB", [(1, 0, 0, 1), (0, 1, 0, 0), (0, 0, 1, 0)])
            sage: (f0 < f1) + (f0 == f1) + (f0 > f1)
            1
            sage: (f1 < f0) + (f1 == f0) + (f1 > f0)
            1
        """
        c = self._constellation_class._cmp_(self, other)
        if c:
            return rich_to_bool(op, c)

        c = subspace_cmp(self._subspace, other._subspace)
        return rich_to_bool(op, c)

    def dimension(self):
        r"""
        Return the dimension of the linear family.

        EXAMPLES::

            sage: from veerer import StrebelGraphLinearFamily
            sage: G = StrebelGraphLinearFamily("(0,1,2)(~0,~1:1,~2:2)", [(1, 1, 0), (1, 0, 1)])
            sage: G.dimension()
            2
        """
        return self._subspace.nrows()

    def constraints_matrix(self, mutable=None):
        r"""
        Return a basis of constraints on x-coordinates as a matrix.

        EXAMPLES::

            sage: from veerer import VeeringTriangulation, StrebelGraph
            sage: vt = VeeringTriangulation("(0,1,2)(~0,~1,~2)", "RRB")
            sage: vt.as_linear_family().constraints_matrix().echelon_form()
            [ 1 -1  1]

            sage: F = StrebelGraph("(0,2,~3,~1)(1)(3,~0)(~2)").add_residue_constraints([[1, 0, 2, 0]])
            sage: F.constraints_matrix().echelon_form()
            [ 1 -1  1  1]
        """
        return self._subspace.right_kernel_matrix()

    def generators_matrix(self, mutable=None):
        r"""
        Return a basis of generators of x-coordinates as a matrix.

        EXAMPLES::

            sage: from veerer import VeeringTriangulation, StrebelGraph
            sage: vt = VeeringTriangulation("(0,1,2)(~0,~1,~2)", "RRB")
            sage: vt.as_linear_family().generators_matrix().echelon_form()
            [ 1  0 -1]
            [ 0  1  1]

            sage: F = StrebelGraph("(0,2,~3,~1)(1)(3,~0)(~2)").add_residue_constraints([[1, 0, 2, 0]])
            sage: F.generators_matrix().echelon_form()
            [ 1  0  0 -1]
            [ 0  1  0  1]
            [ 0  0  1 -1]
        """
        if not self._mutable and not mutable:
            return self._subspace
        else:
            subspace = self._subspace.__copy__()
            if not mutable:
                subspace.set_immutable()
            return subspace

    def residue_constraints(self):
        r"""
        Return a basis of residue constraints.

        If the family is not made of Abelian differentials, a ``ValueError`` is raised.

        For meromorphic differentials, the space of residue constraints is at
        least one-dimensional since the sum of residues is zero.

        EXAMPLES::

            sage: from veerer import StrebelGraph, VeeringTriangulation

            sage: G = StrebelGraph("(0,2,~3,~1)(1)(3,~0)(~2)")
            sage: G.as_linear_family().residue_constraints().echelon_form()
            [1 1 1 1]

            sage: F = G.add_residue_constraints([[1, 2, 0, 0]])
            sage: F.residue_constraints().echelon_form()
            [ 1  0  2  2]
            [ 0  1 -1 -1]

            sage: V = VeeringTriangulation("(0,5,~4)(2,6,~5)(3,~0,7)(4,~3,~1)", boundary="(1:1)(~7:1)(~6:1)(~2:1)", colouring="RRRBBBBR")

            sage: V.as_linear_family().residue_constraints().echelon_form()
            [1 1 1 1]

            sage: F = V.add_residue_constraints([[1, 2, 0, 0]])
            sage: F.residue_constraints().echelon_form()
            [ 1  0  2  2]
            [ 0  1 -1 -1]

        For holomorphic differentials, there is no residue constraint::

            sage: fp = "(0,1,2)(~0,~4,~2)(3,4,5)(~3,~1,~5)"
            sage: cols = "BRRBRR"
            sage: f = VeeringTriangulation(fp, cols).as_linear_family(mutable=True)
            sage: f.residue_constraints()
            []
        """
        # We want vectors that are linear combinations of self.residue_matrix()
        # and self.constraints_matrix().
        residue_matrix = self.residue_matrix()
        intersection = residue_matrix.row_module().intersection(self.constraints_matrix().row_module()).matrix()
        nr = intersection.nrows() + residue_matrix.nrows() - residue_matrix.rank()
        nc = self.num_boundary_faces()
        return matrix(self.base_ring(), nr,  nc, [residue_matrix.solve_left(v) for v in intersection.rows()] + residue_matrix.left_kernel_matrix().rows())

    def stratum(self):
        return self.copy(self, cls=self._constellation_class).stratum()

    def relabel(self, p, check=True):
        r"""
        Relabel inplace the veering triangulation linear family according to the permutation ``p``.

        EXAMPLES:

        Relabelling the subspace as well::

            sage: from veerer import VeeringTriangulations, VeeringTriangulationLinearFamily
            sage: from veerer.permutation import perm_random_centralizer

            sage: vt, s, t = VeeringTriangulations.L_shaped_surface(2, 3, 4, 5, 1, 2)
            sage: f = VeeringTriangulationLinearFamily(vt, [s, t], mutable=True)
            sage: for _ in range(10):
            ....:     p = f._relabelling_from(choice(list(f.half_edges())))
            ....:     f.relabel(p)
            ....:     f._check()

            sage: for _ in range(10):
            ....:     p = perm_random_centralizer(f.edge_permutation(copy=False))
            ....:     f.relabel(p)
            ....:     f._check()
        """
        m = self.num_edges()
        if check and not perm_check(p, 2 * self._ne):
            p = perm_init(p, 2 * self._ne, edge_like=True)
            if not perm_check(p, 2 * self._ne):
                raise ValueError('invalid relabelling permutation')

        rr = perm_relabel_on_edges(p, self._ne)[0]
        matrix_permutation(self._subspace, rr)
        self._subspace.echelonize()
        self._constellation_class.relabel(self, p, False)

    def best_relabelling(self, return_all=False):
        r"""
        Return the smallest relabelling of this linear family.

        EXAMPLES::

            sage: from veerer import VeeringTriangulation, StrebelGraph, VeeringTriangulationLinearFamily, StrebelGraphLinearFamily


            sage: f = VeeringTriangulationLinearFamily("(0,1,2)(~0,~1,3)(~7,10,11)(~8,13,14)(~9,~13,~14)(~10,~11,~12)(~2:1,~6:1,8:1,5:1)(~3:1,6:1,9:1,~5:1)(4:1,12:1)(~4:1,7:1)", "RBBBBBBBBBRBBRB", [(1, 0, -1, -1, 0, 0, 0, -2, -1, -1, 2, 0, -2, 1, 0), (0, 1, 1, 1, 0, 0, 0, 2, 1, 1, 0, 2, 2, 0, 1), (0, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0)])
            sage: len(f.best_relabelling(return_all=True)[0])
            8

            sage: f = StrebelGraphLinearFamily("(0,2,3,1,5,6)(~0,~5,7,~8,~2,~6)(~1,4,~3)(~4,~7,8)", [(2, 1, 0, 0, 2, 0, 0, 0, 1), (0, 0, 1, 0, 2, 1, 0, 0, 0), (0, 0, 0, 1, 2, 0, 2, 1, 0)])
            sage: len(f.best_relabelling(return_all=True)[0])
            2
        """
        ne = self._ne
        n = 2 * ne
        relabellings, fp_best, half_edges_data_best, edges_data_best = self.constellation().best_relabelling(return_all=True)

        subspace_best = copy(self._subspace)
        relabelling_best = relabellings[0]
        r = perm_relabel_on_edges(relabelling_best, ne)[0]
        matrix_permutation(subspace_best, r)
        subspace_best.echelonize()
        if return_all:
            family_relabellings = [relabelling_best]

        for i in range(1, len(relabellings)):
            relabelling_new = relabellings[i]
            subspace_new = copy(self._subspace)
            r = perm_relabel_on_edges(relabelling_new, ne)[0]
            matrix_permutation(subspace_new, r)
            subspace_new.echelonize()
            if subspace_new < subspace_best:
                relabelling_best = relabelling_new
                subspace_best = subspace_new
                if return_all:
                    family_relabellings.clear()
                    family_relabellings.append(relabelling_new)
            elif return_all and subspace_new == subspace_best:
                family_relabellings.append(relabelling_new)

        return (family_relabellings, fp_best, half_edges_data_best, edges_data_best, subspace_best) if return_all else (relabelling_best, fp_best, half_edges_data_best, edges_data_best, subspace_best)

    def set_canonical_labels(self, mapping=False):
        r"""
        Set labels in a canonical way in its automorphism class.
        """
        if not self._mutable:
            raise ValueError('immutable triangulation; use a mutable copy instead')

        r, fp_best, half_edges_data_best, edges_data_best, subspace_best = self.best_relabelling()
        self._fp = fp_best
        self._vp = perm_conjugate(self._vp, r)
        self._half_edges_data = half_edges_data_best
        self._edges_data = edges_data_best
        self._set_data_pointers()
        self._subspace = subspace_best
        if mapping:
            return r

    def _non_isom_easy(self, other):
        return (self._constellation_class._non_isom_easy(self, other) or
                self._subspace.nrows() != other._subspace.nrows())

    def as_linear_family(self, mutable=False):
        if not mutable and not self._mutable:
            return self
        return self.copy(mutable)

    def abelian_cover(self, mutable=False):
        r"""
        Return the Abelian double cover.

        EXAMPLES::

            sage: from veerer.linear_family import VeeringTriangulationLinearFamilies, StrebelGraphLinearFamily

            sage: X9 = VeeringTriangulationLinearFamilies.prototype_H1_1(0, 2, 1, -1)
            sage: Y9 = X9.abelian_cover() # not tested
            sage: Y9.dimension() == X9.dimension() # not tested
            True
            sage: Y9.stratum()  # optional - surface_dynamics # not tested
            H_2(1^2)

            sage: F = StrebelGraphLinearFamily("(0,1:1,~0,~1:1)", [[2, 1]])
            sage: Fab = F.abelian_cover() # not tested
            sage: Fab # not tested
            StrebelGraphLinearFamily("(0,~2:1,~0,2:1)(1:1,3,~1:1,~3)", [(2, 1, 1, 2)])
            sage: print(F.stratum(), Fab.stratum())  # optional - surface_dynamics # not tested
            H_1(2, -2) (H_1(2, -2), H_1(2, -2))
        """
        t, inv, quot = self._constellation_class.abelian_cover(self, involution_and_quotient=True)
        assert t.num_edges() == 2 * self._ne - self.num_folded_edges()
        nr = self._subspace.nrows() + self.num_edges() - self.num_folded_edges()
        # TODO: we have equations coming from the quotient and equations coming from the involution
        raise NotImplementedError

    def quotient(self, blocks, mapping=False, mutable=False, check=True):
        r"""
        EXAMPLES::

            sage: from veerer import VeeringTriangulation, VeeringTriangulationLinearFamily
            sage: vt = VeeringTriangulation("(0,1,2)(3,4,~0)(5,6,~1)(7,~2,8)(9,~3,~6)(10,~7,~4)(11,~5,12)(13,14,~8)(15,~9,16)(17,18,~10)(19,~17,~11)(20,~13,~12)(21,~14,~18)(22,~21,~15)(23,24,~16)(25,~23,~19)(26,~20,~25)(~26,~24,~22)", "RBBRBRBRRBRBBRBBRRBRRRBBRRB")
            sage: subspace = [(1, 0, -1, 0, -1, 0, 0, 0, 1, 0, 1, -1, -1, 0, -1, 0, 0, 0, -1, 1, 1, 0, 0, -1, 1, 0, -1),
            ....:        (0, 1, 1, 0, 0, 1, 2, 0, -1, 2, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, -1, 1, 1, 0, 0, 0, 1),
            ....:        (0, 0, 0, 1, 1, 1, 1, 0, 0, 0, -1, 1, 2, 2, 2, 1, 1, 0, 1, -1, 0, 1, 0, 1, 0, 0, 0),
            ....:        (0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 2, 1, 0, 0, 2, 1, 1, 1, 0, 0, 0, 0, 1, 0)]
            sage: f = VeeringTriangulationLinearFamily(vt, subspace)
            sage: f.automorphism_quotient()
            VeeringTriangulationLinearFamily("(0,1,2)(~0,3,4)(~1,5,6)(~2,8,7)(~3,~6,9)(~4,10,~7)(~5,12,11)(~8,13,~12)(~10,14,~11)", "RBBRBRBRRBRBBRR", [(1, 0, -1, 0, -1, 0, 0, 0, 1, 0, 1, -1, -1, 0, 0), (0, 1, 1, 0, 0, 1, 2, 0, -1, 2, 0, 0, 1, 0, 0), (0, 0, 0, 1, 1, 1, 1, 0, 0, 0, -1, 1, 2, 2, 0), (0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 2, 2)])
        """
        constellation_quotient, mapping = self.constellation().quotient(blocks, True, mutable, check)

        if check:
            for block in blocks:
                for gen in self._subspace.rows():
                    if len(set(gen[h // 2] for h in block)) != 1:
                        raise ValueError("invalid blocks")

        subspace = matrix(self.base_ring(), self._subspace.nrows(), constellation_quotient._ne)
        for i in range(self._subspace.nrows()):
            for block in blocks:
                subspace[i, mapping[block[0]] // 2] = self._subspace[i, block[0] // 2]

        return self.__class__(constellation_quotient, subspace, mutable=mutable, check=check)


class VeeringTriangulationLinearFamily(LinearFamily, VeeringTriangulation):
    r"""
    Veering triangulation together with a subspace of H^1(S, Sigma; \bR) that
    describes a (piece of a) linear GL(2,R)-invariant immersed sub-orbifold.
    """
    __slots__ = ['_constellation_class', '_subspace']


    def _horizontal_subspace(self):
        mat = copy(self._subspace)
        ne = self.num_edges()
        for j in range(ne):
            if self._colouring[j] == BLUE:
                for i in range(mat.nrows()):
                    mat[i, j] *= -1
        return mat

    def generators_matrix(self, slope=VERTICAL, mutable=None):
        if slope == VERTICAL:
            if not self._mutable and not mutable:
                return self._subspace
            else:
                subspace = self._subspace.__copy__()
                if not mutable:
                    subspace.set_immutable()
                return subspace
        elif slope == HORIZONTAL:
            subspace = self._horizontal_subspace()
            if not mutable:
                subspace.set_immutable()
            return subspace
        else:
            raise ValueError

    def rotate(self):
        r"""
        Conjugate this family.

        EXAMPLES::

            sage: from veerer import *

            sage: fp = "(0,1,2)(~0,~4,~2)(3,4,5)(~3,~1,~5)"
            sage: cols = "BRRBRR"
            sage: f = VeeringTriangulation(fp, cols).as_linear_family(mutable=True)
            sage: f.rotate()
            sage: f
            VeeringTriangulationLinearFamily("(0,1,2)(~0,~4,~2)(~1,~5,~3)(3,4,5)", "RBBRBB", [(1, 0, -1, 0, 0, 0), (0, 1, 1, 0, 1, 1), (0, 0, 0, 1, 0, -1)])

            sage: fp = "(0,12,~11)(1,13,~12)(2,14,~13)(3,15,~14)(4,17,~16)(5,~10,11)(6,~3,~17)(7,~2,~6)(8,~5,~7)(9,~0,~8)(10,~4,~9)(16,~15,~1)"
            sage: cols = "RRRRRRBBBBBBBBBBBB"
            sage: f = VeeringTriangulation(fp, cols).as_linear_family(mutable=True)
            sage: f.rotate()
            sage: f
            VeeringTriangulationLinearFamily("(0,12,~11)(~0,~8,9)(1,13,~12)(~1,16,~15)(2,14,~13)(~2,~6,7)(3,15,~14)(~3,~17,6)(4,17,~16)(~4,~9,10)(5,~10,11)(~5,~7,8)", "BBBBBBRRRRRRRRRRRR", [(1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0), (0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 2, 2, 1, 1, 1, 0, 0), (0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0), (0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1), (0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0), (0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)])
        """
        if not self._mutable:
            raise ValueError('immutable veering triangulation family; use a mutable copy instead')

        subspace = self._horizontal_subspace()
        subspace.echelonize()
        self._subspace = subspace
        super().rotate()

        # TODO: remove check
        self._check()

    def _set_subspace_constraints(self, insert, x, slope):
        ambient_dim = self._subspace.ncols()
        if slope == VERTICAL:
            subspace = self._subspace
        elif slope == HORIZONTAL:
            subspace = self._horizontal_subspace()
        for row in subspace.right_kernel_matrix():
            insert(sum(row[i] * x[i] for i in range(ambient_dim)) == 0)

    def _set_subspace_constraints_fast(self, cs, L, slope):
        zero = L.base_ring().zero()
        if slope == VERTICAL:
            subspace = self._subspace
            for row in subspace.right_kernel_matrix():
                cs.insert(LinearConstraint(op_EQ, L.element_class(L, row.dict(), zero)), check=False)
        elif slope == HORIZONTAL:
            subspace = self._horizontal_subspace()
            shift = self.num_edges()
            for row in subspace.right_kernel_matrix():
                cs.insert(LinearConstraint(op_EQ, L.element_class(L, {key + shift: value for key, value in row.dict().items()}, zero)), check=False)

    def _check(self, error=ValueError):
        LinearFamily._check(self, error)

        # test that elements satisfy the switch condition
        subspace = self._subspace
        for v in subspace.rows():
            self._set_switch_conditions(self._constraint_check, v, VERTICAL)

    def train_track_polytope(self, slope=VERTICAL, low_bound=0, backend=None):
        r"""
        Return the polytope of non-negative elements in the subspace.

        EXAMPLES::

            sage: from veerer import *
            sage: vt, s, t = VeeringTriangulations.L_shaped_surface(1, 3, 1, 1)
            sage: f = VeeringTriangulationLinearFamily(vt, [s, t])
            sage: f.train_track_polytope(VERTICAL)
            Cone of dimension 2 in ambient dimension 7 made of 2 facets (backend=ppl)
            sage: f.train_track_polytope(HORIZONTAL)
            Cone of dimension 2 in ambient dimension 7 made of 2 facets (backend=ppl)

            sage: sorted(f.train_track_polytope(VERTICAL).rays())
            [[0, 1, 3, 3, 1, 1, 0], [1, 0, 0, 1, 1, 1, 1]]
            sage: sorted(f.train_track_polytope(HORIZONTAL).rays())
            [[1, 0, 0, 1, 1, 1, 1], [3, 1, 3, 0, 2, 2, 3]]
        """
        ne = self.num_edges()
        L = LinearExpressions(self.base_ring())
        cs = ConstraintSystem()
        for i in range(ne):
            cs.insert(L.variable(i) >= low_bound)
        self._set_subspace_constraints(cs.insert, [L.variable(i) for i in range(ne)], slope)
        return cs.cone(backend)

    def flip(self, e, col, check=True):
        r"""
        EXAMPLES::

            sage: from veerer import *

            sage: T, s, t = VeeringTriangulations.L_shaped_surface(1, 1, 1, 1)

            sage: L = VeeringTriangulationLinearFamily(T, [s, t], mutable=True)
            sage: T = T.copy(mutable=True)

            sage: T.flip(3, 2)
            sage: L.flip(3, 2)
            sage: T
            VeeringTriangulation("(0,3,2)(~0,1,4)(~1,5,6)", "BRRBBBB")
            sage: L
            VeeringTriangulationLinearFamily("(0,3,2)(~0,1,4)(~1,5,6)", "BRRBBBB", [(1, 0, 0, 1, 1, 1, 1), (0, 1, 1, -1, 1, 1, 0)])

            sage: L.flip(4, 2)
            sage: T.flip(4, 2)
            sage: T
            VeeringTriangulation("(0,3,2)(~0,4,1)(~1,5,6)", "BRRBBBB")
            sage: L
            VeeringTriangulationLinearFamily("(0,3,2)(~0,4,1)(~1,5,6)", "BRRBBBB", [(1, 0, 0, 1, 1, 1, 1), (0, 1, 1, -1, -1, 1, 0)])

            sage: T.flip(5, 2)
            sage: L.flip(5, 2)
            sage: T
            VeeringTriangulation("(0,3,2)(~0,4,1)(~1,6,5)", "BRRBBBB")
            sage: L
            VeeringTriangulationLinearFamily("(0,3,2)(~0,4,1)(~1,6,5)", "BRRBBBB", [(1, 0, 0, 1, 1, 1, 1), (0, 1, 1, -1, -1, -1, 0)])
        """
        super().flip(e, col, Gx=self._subspace, check=check)
        self._subspace.echelonize()

    def flip_back(self, e, col, check=True):
        super().flip_back(e, col, Gx=self._subspace, check=check)
        self._subspace.echelonize()

    def is_cylindrical(self, col=None):
        r"""
        Return whether this linear family consists of a union of cylinders
        whose moduli are allowed to degenerate to infinity.

        EXAMPLES::

            sage: from veerer import RED, VeeringTriangulation, VeeringTriangulationLinearFamily
            sage: faces = "(0,~2,1)(2,6,~3)(3,5,4)"
            sage: cols = "RBRRBRB"
            sage: K = QuadraticField(5, 'sqrt5')
            sage: sqrt5 = K.gen()
            sage: x = (1, 0, 1, 1/2*sqrt5 + 1/2, -1, 1/2*sqrt5 - 1/2, -1/2*sqrt5 + 1/2)
            sage: y = (0, 1, 1, 0, 1/2*sqrt5 - 1/2, 1/2*sqrt5 - 1/2, 1)
            sage: f = VeeringTriangulationLinearFamily(faces, cols, [x, y])
            sage: f.is_cylindrical(RED)
            False
            sage: VeeringTriangulation.is_cylindrical(f, RED)
            True
        """
        if col is None:
            return self.is_cylindrical(BLUE) or self.is_cylindrical(RED)
        if col != RED and col != BLUE:
            raise ValueError("'col' must be one of RED or BLUE")
        if not super().is_cylindrical(col):
            return False
        cylinders = list(self.cylinders(col))

        C = []  # middle edges
        for cyl in cylinders:
            c = [0] * self._ne
            for e in cyl[0]:
                c[e // 2] = 1
            C.append(c)

        # take intersection of the cylinder twists in the tangent space
        F = FreeModule(self.base_ring(), self.num_edges())
        H = F.submodule(self._subspace).intersection(F.submodule(C))

        mid_edges = set(i for c in C for i, j in enumerate(c) if j)
        for b in H.basis_matrix():
            for i, j in enumerate(b):
                if j:
                    mid_edges.discard(i)
        return not mid_edges

    def random_forward_flip(self, repeat=1):
        r"""
        Apply a random forward flip randomly among the ones that keeps the family core.

        INPUT:

        - ``repeat`` - integer (default 1) - if provided, make ``repeat`` flips instead
          of 1

        EXAMPLES::

            sage: from veerer.linear_family import VeeringTriangulationLinearFamilies
            sage: X = VeeringTriangulationLinearFamilies.prototype_H1_1(0, 4, 1, 0, mutable=True)
            sage: X.is_core()
            True
            sage: X.is_delaunay()
            False
            sage: while not X.is_delaunay():
            ....:     X.random_forward_flip()
        """
        if not self._mutable:
            raise ValueError('immutable veering triangulation family; use a mutable copy instead')

        cols = [RED, BLUE]
        for _ in range(repeat):
            e = choice(self.forward_flippable_edges())
            old_col = self._colouring[e // 2]
            shuffle(cols)
            for c in cols:
                self.flip(e, c)
                # NOTE: for veering triangulation, the following check is made much faster
                # with edge_has_curve. However for families, we have additional linear
                # constraints on the curve that makes it harder to build.
                if self.is_core():
                    break
                else:
                    self.flip_back(e, old_col)

    def strebel_graph(self, slope=VERTICAL, mapping=False, mutable=False):
        r"""
        EXAMPLES::

            sage: from veerer import *

            sage: triangles = "(0,1,2)(~1,3,4)(~3,5,6)(~6,7,8)"
            sage: boundary = "(~0:1,~2:1,~4:1,~8:1,~7:1,~5:1)"
            sage: colours = "BBRRRRBRB"
            sage: vt = VeeringTriangulation(triangles, boundary, colours)
            sage: v0,v1,v2,v3,v4 = vt.as_linear_family()._subspace.rows()
            sage: VeeringTriangulationLinearFamily(vt, [v0 + v1 + v2 + v3 + v4]).strebel_graph()
            StrebelGraphLinearFamily("(0,1,~1:1,~0,2,~3,4,~4:1,3,~2)", [(1, 0, 1, 0, 1)])
            sage: VeeringTriangulationLinearFamily(vt, [v0 + v1 + v2, v3 + v4]).strebel_graph()
            StrebelGraphLinearFamily("(0,1,~1:1,~0,2,~3,4,~4:1,3,~2)", [(1, 0, 1, 0, 1), (0, 0, 0, 1, 1)])
            sage: VeeringTriangulationLinearFamily(vt, [v0, v1 + v2, v3 + v4]).strebel_graph()
            StrebelGraphLinearFamily("(0,1,~1:1,~0,2,~3,4,~4:1,3,~2)", [(1, 0, 1, 0, 1), (0, 1, 0, 0, 0), (0, 0, 0, 1, 1)])

            sage: vt = VeeringTriangulation("(1,4,~2)(2,~6,~3)(3,~5,~4)", boundary="(0:1)(5:1)(6:1)(~1:1,~0:1)", colouring="BBRRBBB")
            sage: F = VeeringTriangulationLinearFamily(vt, [(1, 2, 0, -1, 2, 1, 1), (0, 0, 1, 1, -1, 0, 0)])
            sage: F
            VeeringTriangulationLinearFamily("(1,4,~2)(2,~6,~3)(3,~5,~4)(0:1)(~0:1,~1:1)(5:1)(6:1)", "BBRRBBB", [(1, 2, 0, -1, 2, 1, 1), (0, 0, 1, 1, -1, 0, 0)])
            sage: F.strebel_graph()
            StrebelGraphLinearFamily("(0)(~0,2,~3,~1)(1,~2)(3)", [(1, 0, 1, 1), (0, 1, -1, 0)])

            sage: vt = VeeringTriangulation("(0,5,~4)(2,6,~5)(3,~0,7)(4,~3,~1)", boundary="(1:1)(~7:1)(~6:1)(~2:1)", colouring="RRRBBBBB")
            sage: f1 = vt.add_residue_constraints([[1, 1, 1, 0]])
            sage: f1.strebel_graph().residue_constraints().echelon_form()
            [1 0 1 1]
            [0 1 0 0]

        An example with folded edges::

            sage: x = polygen(QQ)
            sage: K.<sqrt17> = NumberField(x^2 - 17, embedding=AA(17).sqrt())
            sage: vt = VeeringTriangulation("", boundary="(0:1)(1:1,~0:1)", colouring="RR")
            sage: f = VeeringTriangulationLinearFamily(vt, [(1, 1/4*sqrt17 - 3/4)])
            sage: f.strebel_graph()
            StrebelGraphLinearFamily("(0)(~0,1)", [(1, 1/4*sqrt17 - 3/4)])
        """
        indices = []
        fp = self._fp
        for e in range(self._ne):
            if self.is_half_edge_strebel(2 * e, slope) and (fp[2 * e + 1] == -1 or self.is_half_edge_strebel(2 * e + 1)):
                indices.append(e)

        G, index_strebel, index_non_strebel = VeeringTriangulation.strebel_graph(self, slope, mapping=True, mutable=False)
        subspace = self.generators_matrix(slope).matrix_from_columns(indices)
        sg = StrebelGraphLinearFamily(G, subspace, mutable=mutable)
        return (sg, index_strebel, index_non_strebel) if mapping else sg


class StrebelGraphLinearFamily(LinearFamily, StrebelGraph):
    r"""
    EXAMPLES::

        sage: from veerer import StrebelGraphLinearFamily
        sage: G = StrebelGraphLinearFamily("(0,1,2)(~0,~1:1,~2:2)", [(1, 1, 0), (1, 0, 1)])
        sage: G
        StrebelGraphLinearFamily("(0,1,2)(~0,~1:1,~2:2)", [(1, 0, 1), (0, 1, -1)])
        sage: G.dimension()
        2
    """
    __slots__ = ['_constellation_class', '_subspace']

    def is_core(self):
        r"""
        Return whether this linear family of Strebel graphs is core.

        A linear family of Strebel graphs is core if it has a positive solution
        (ie a non-degenerate edge-length vector).

        EXAMPLES::

            sage: from veerer import StrebelGraphLinearFamily

            sage: G = StrebelGraphLinearFamily("(0,1,2)(~0,~1:1,~2:2)", [(1, 1, 0), (-1, 0, 2)])
            sage: G.is_core()
            True

            sage: G = StrebelGraphLinearFamily("(0,1,2)(~0,~1:1,~2:2)", [(1, 1, -1), (-1, 0, 1)])
            sage: G.is_core()
            False
        """
        return self.cone().affine_dimension() == self.dimension()

    def _set_subspace_constraints(self, insert, x):
        ambient_dim = self._subspace.ncols()
        subspace = self._subspace
        for row in subspace.right_kernel_matrix():
            insert(sum(row[i] * x[i] for i in range(ambient_dim)) == 0)

    def cone(self, backend=None):
        r"""
        Return the cone of of x-coordinates for this linear family.

        EXAMPLES::

            sage: from veerer import StrebelGraph
            sage: F = StrebelGraph("(0,2,~3,~1)(1)(3,~0)(~2)").add_residue_constraints([[0, 1, -1, 0], [0, 1, 0, -1]])
            sage: F.cone(backend='ppl')
            Cone of dimension 2 in ambient dimension 4 made of 2 facets (backend=ppl)
            sage: F.cone(backend='sage')
            Cone of dimension 2 in ambient dimension 4 made of 2 facets (backend=sage)
            sage: F.cone(backend='normaliz-QQ')  # optional - pynormaliz
            Cone of dimension 2 in ambient dimension 4 made of 2 facets (backend=normaliz-QQ)
        """
        from .polyhedron import LinearExpressions, ConstraintSystem
        L = LinearExpressions(self.base_ring())
        ne = self.num_edges()
        x = [L.variable(i) for i in range(ne)]
        cs = ConstraintSystem(ne)
        self._set_strebel_constraints(cs.insert, x)
        self._set_subspace_constraints(cs.insert, x)
        return cs.cone(backend=backend)

    def add_residue_constraints(self, residue_constraints):
        r"""
        Return the Strebel graph linear family obtained by adding the given
        linear constraints on the residues.

        Note that the resulting family might not intersect the relative
        interior of the Strebel cone. To check whether this is the case, use
        the method ``is_core``.

        EXAMPLES::

            sage: from veerer import StrebelGraph
            sage: G = StrebelGraph("(0,2,~3,~1)(1)(3,~0)(~2)")
            sage: f1 = G.add_residue_constraints([[0, 1, -1, 0]]).add_residue_constraints([[0, 1, 0, -1]])
            sage: f2 = G.add_residue_constraints([[0, 1, -1, 0], [0, 1, 0, -1]])
            sage: f1 == f2
            True
        """
        if not isinstance(residue_constraints, Matrix):
            residue_constraints = matrix(residue_constraints)

        base_ring = cm.common_parent(self.base_ring(), residue_constraints.base_ring())
        nr = self._subspace.nrows()
        nc = self._subspace.ncols()
        constraint_matrix = matrix(base_ring, (nc - nr) + residue_constraints.nrows(), self.num_edges())
        constraint_matrix[:nc - nr, :] = self._subspace.right_kernel_matrix()
        constraint_matrix[nc - nr:, :] = residue_constraints * self.residue_matrix()
        gens = constraint_matrix.right_kernel_matrix()
        from .linear_family import StrebelGraphLinearFamily
        return StrebelGraphLinearFamily(self, gens)

    def veering_triangulations(self, colouring, slope=VERTICAL, mutable=False):
        r"""
        EXAMPLES::

            sage: from veerer import StrebelGraphLinearFamily
            sage: G = StrebelGraphLinearFamily("(0,1,2)(~0,~1:1,~2:2)", [(1, 1, 0), (1, 0, 1)])
            sage: for colouring in G.colourings():
            ....:     print(colouring, sum(1 for _ in G.veering_triangulations(colouring)), sum(1 for _ in G.delaunay_triangulations(colouring)))
            ....:     assert all(vt.strebel_graph() == G for vt in G.veering_triangulations(colouring))
            ....:     assert all(vt.strebel_graph() == G for vt in G.delaunay_triangulations(colouring))
            array('i', [1, 1, 1]) 1 1
            array('i', [1, 1, 2]) 6 2
            array('i', [1, 2, 1]) 3 1
            array('i', [1, 2, 2]) 6 0
            array('i', [2, 1, 1]) 3 0
            array('i', [2, 1, 2]) 3 2
            array('i', [2, 2, 1]) 3 1
            array('i', [2, 2, 2]) 1 1
        """
        for vt in StrebelGraph.veering_triangulations(self, colouring, slope, mutable):
            switch = vt.generators_matrix(mutable=True)
            switch.echelonize()
            assert switch[:self.num_edges(), :self.num_edges()].is_one()
            subspace = []
            for row in self._subspace.rows():
                subspace.append(sum(x * switch.row(i) for i, x in enumerate(row)))
            yield VeeringTriangulationLinearFamily(vt, subspace, mutable=mutable)


class VeeringTriangulationLinearFamilies:
    r"""
    A collection of linear families.
    """
    @staticmethod
    def H2_prototype_parameters(D, spin=None):
        r"""
        Return the list of prototypes in a given discriminant ``D``.

        If ``spin`` is provided, then return only the prototypes with the given
        spin parameter.

        EXAMPLES::

            sage: from veerer.linear_family import VeeringTriangulationLinearFamilies
            sage: list(VeeringTriangulationLinearFamilies.H2_prototype_parameters(5))
            [(0, 1, 1, -1)]
            sage: list(VeeringTriangulationLinearFamilies.H2_prototype_parameters(8))
            [(0, 2, 1, 0), (0, 1, 1, -2)]
            sage: list(VeeringTriangulationLinearFamilies.H2_prototype_parameters(9))
            [(0, 2, 1, -1)]
            sage: list(VeeringTriangulationLinearFamilies.H2_prototype_parameters(12))
            [(0, 3, 1, 0), (0, 1, 2, -2), (0, 2, 1, -2)]
            sage: list(VeeringTriangulationLinearFamilies.H2_prototype_parameters(13))
            [(0, 3, 1, 1), (0, 3, 1, -1), (0, 1, 1, -3)]
            sage: list(VeeringTriangulationLinearFamilies.H2_prototype_parameters(16))
            [(0, 4, 1, 0),  (0, 3, 1, -2)]

            sage: list(VeeringTriangulationLinearFamilies.H2_prototype_parameters(17, spin=0))
            [(1, 2, 2, -1), (0, 4, 1, 1), (0, 2, 1, -3)]
            sage: list(VeeringTriangulationLinearFamilies.H2_prototype_parameters(17, spin=1))
            [(0, 2, 2, -1), (0, 4, 1, -1), (0, 1, 2, -3)]
        """
        # NOTE: for the spin computation, decompose D = E f^2 and the spin is
        #  (e - f) / 2 + (c + 1)(a + b + a*b) mod 2

        from sage.rings.integer_ring import ZZ

        if not isinstance(D, numbers.Integral):
            raise ValueError('D must be an integer')
        D = ZZ(D)
        if D <= 4 or not D % 4 in [0, 1]:
            raise ValueError('D must be an integer > 4 congruent to either 0 or 1 mod 4')

        if spin is not None:
            if D % 8 != 1:
                raise ValueError('spin can only be specified if D is congruent to 1 mod 8')
            if not isinstance(spin, numbers.Integral):
                raise ValueError('spin must be an integer')
            spin = ZZ(spin)
            if spin not in [0, 1]:
                raise ValueError('spin must either be 0 or 1')

        E = D.squarefree_part()
        f = (D // E).sqrtrem()[0]

        e = D % 4
        while e**2 < D:
            assert (D - e**2) % 4 == 0
            bc = (D - e**2) // 4
            for b in bc.divisors():
                c = bc // b
                # need c + e < b
                if e == 0:
                    signs = (1,)
                else:
                    signs = (1, -1)
                for s in signs:
                    if c + s*e < b:
                        for a in range(gcd(b, c)):
                            if gcd([a, b, c, e]) == 1:
                                if spin is None or ((s*e - f) // 2 + (c + 1) * (a + b + a*b)) % 2 == spin:
                                    yield (a, b, c, s*e)
            e += 2

    @staticmethod
    def prototype_H2(a, b, c, e, mutable=False):
        r"""
        Return the Mcmullen prototype with parameters ``(a, b, c, e)`` or rather
        its quotient in `Q(1, -1^5)`.

        EXAMPLES::

            sage: from veerer.linear_family import VeeringTriangulationLinearFamilies

            sage: X9 = VeeringTriangulationLinearFamilies.prototype_H2(0, 2, 1, -1)
            sage: X9.base_ring()
            Rational Field
            sage: X9.is_delaunay()
            True
            sage: X9.delaunay_automaton()
            Delaunay automaton with 6 states

            sage: X17 = VeeringTriangulationLinearFamilies.prototype_H2(0, 2, 2, -1)
            sage: X17.base_ring()
            Number Field in sqrt17 with defining polynomial x^2 - 17 with sqrt17 = 4.123105625617660?
            sage: X17.is_delaunay()
            True
            sage: X17.delaunay_automaton() # long time
            Delaunay automaton with 210 states

        We check below part of McMullen theorem about connectedness::

            sage: a0, b0, c0, e0 = next(VeeringTriangulationLinearFamilies.H2_prototype_parameters(17, spin=0))
            sage: X17_0 = VeeringTriangulationLinearFamilies.prototype_H2(a0, b0, c0, e0)
            sage: A0 = X17_0.delaunay_automaton()  # long time
            sage: for a, b, c, e in VeeringTriangulationLinearFamilies.H2_prototype_parameters(17, spin=0):  # long time
            ....:     X = VeeringTriangulationLinearFamilies.prototype_H2(a, b, c, e, mutable=True)
            ....:     X.set_canonical_labels()
            ....:     X.set_immutable()
            ....:     assert X in A0

            sage: a1, b1, c1, e1 = next(VeeringTriangulationLinearFamilies.H2_prototype_parameters(17, spin=1))
            sage: X17_1 = VeeringTriangulationLinearFamilies.prototype_H2(a1, b1, c1, e1)
            sage: A1 = X17_1.delaunay_automaton()  # long time
            sage: for a, b, c, e in VeeringTriangulationLinearFamilies.H2_prototype_parameters(17, spin=1):  # long time
            ....:     X = VeeringTriangulationLinearFamilies.prototype_H2(a, b, c, e, mutable=True)
            ....:     X.set_canonical_labels()
            ....:     X.set_immutable()
            ....:     assert X in A1
        """
        #         (a,c)
        #           x-------x---------x  (a+b,c)
        #          /                 /
        #         /                 /
        # (0,0)  x-------x---------x  (b,0)
        #        |       |
        #        |       |
        #        |       |
        #        x-------x
        #     (0,-lbda)    (lbda,-lbda)
        from sage.rings.integer_ring import ZZ
        from sage.rings.rational_field import QQ
        from sage.rings.number_field.number_field import NumberField
        from sage.rings.qqbar import AA
        if not all(isinstance(x, numbers.Integral) for x in (a, b, c, e)):
            raise ValueError('a, b, c, e must be integers')
        a = ZZ(a)
        b = ZZ(b)
        c = ZZ(c)
        e = ZZ(e)
        if not (0 < b and 0 < c and 0 <= a < gcd(b, c) and c + e < b and gcd([a, b, c, e]) == 1):
            raise ValueError('a, b, c, e must satisfy: 0 < b, 0 < c, 0 <= a < gcd(b, c), c + e < b and gcd(a, b, c, e) = 1')
        D = e**2 + 4*b*c
        if D.is_square():
            K = QQ
            sqrtD = D.sqrtrem()[0]
        else:
            E = D.squarefree_part()
            f = (D // E).sqrtrem()[0]
            x = QQ['x'].gen()
            K = NumberField(x**2 - E, 'sqrt%d' % E, embedding=AA(E).sqrt())
            sqrtD = f * K.gen()

        assert sqrtD**2 == D

        lbda = (e + sqrtD) / 2

        fp = "(~0,5,6)(0,2,4)(~2,3,1)"
        cols = "BBRRRRR"
        vt = VeeringTriangulation(fp, cols, mutable=mutable)

        sx = (lbda, b-lbda, a, b+a-lbda, lbda+a, 0, lbda)
        sy = (0, 0, c, c, c, lbda, lbda)

        return VeeringTriangulationLinearFamily(vt, [sx, sy], mutable=mutable)

    @staticmethod
    def prototype_H1_1(a, b, c, e, mutable=False):
        r"""
        EXAMPLES::

            sage: from veerer.linear_family import VeeringTriangulationLinearFamilies

            sage: X9 = VeeringTriangulationLinearFamilies.prototype_H1_1(0, 2, 1, -1)
            sage: X9.base_ring()
            Rational Field
            sage: X9.delaunay_automaton()  # long time ~3.5secs
            Delaunay automaton with 1244 states
        """
        #         (a+r,c)         (a+b,c)
        #           x-------x------o--x  (a+b+r,c)
        #          /                 /
        #         /                 /
        # (0,0)  o-------o--x------o  (b+r,0)
        #        \        \   (lbda+r,0)
        #         \        \
        #          \        \
        #           x--------x
        #     (r,-lbda)    (lbda+r,-lbda)
        from sage.rings.integer_ring import ZZ
        from sage.rings.rational_field import QQ
        from sage.rings.number_field.number_field import NumberField
        from sage.rings.qqbar import AA
        if not all(isinstance(x, numbers.Integral) for x in (a, b, c, e)):
            raise ValueError('a, b, c, e must be integers')
        a = ZZ(a)
        b = ZZ(b)
        c = ZZ(c)
        e = ZZ(e)
        if not (0 < b and 0 < c and 0 <= a < gcd(b, c) and c + e < b and gcd([a, b, c, e]) == 1):
            raise ValueError('a, b, c, e must satisfy: 0 < b, 0 < c, 0 <= a < gcd(b, c), c + e < b and gcd(a, b, c, e) = 1')
        D = e**2 + 4*b*c
        if D.is_square():
            K = QQ
            sqrtD = D.sqrtrem()[0]
        else:
            E = D.squarefree_part()
            f = (D // E).sqrtrem()[0]
            x = QQ['x'].gen()
            K = NumberField(x**2 - E, 'sqrt%d' % E, embedding=AA(E).sqrt())
            sqrtD = f * K.gen()

        assert sqrtD**2 == D

        lbda = (e + sqrtD) / 2

        fp = "(0,3,8)(~0,5,6)(~3,4,2)(~4,1,7)"
        cols = "BBBRRRRRR"
        vt = VeeringTriangulation(fp, cols, mutable=mutable)

        sx = (lbda, 0, b-lbda, a, a+b-lbda, 0, lbda, a+b-lbda, lbda+a)
        sy = (0, 0, 0, c, c, lbda, lbda, c, c)
        sr = (0, 1, -1, 1, 0, -1, -1, -1, 1)

        return VeeringTriangulationLinearFamily(vt, [sx, sy, sr], mutable=mutable)

    @staticmethod
    def L_shaped_surface(a1, a2, b1, b2, t1=0, t2=0):
        vt, s, t = VeeringTriangulations.L_shaped_surface(a1, a2, b1, b2, t1, t2)
        return VeeringTriangulationLinearFamily(vt, matrix([s, t]))

    @staticmethod
    def triangle_3_4_13_unfolding_orbit_closure():
        r"""
        EXAMPLES::

            sage: from veerer.linear_family import VeeringTriangulationLinearFamilies
            sage: f = VeeringTriangulationLinearFamilies.triangle_3_4_13_unfolding_orbit_closure()
            sage: f
            VeeringTriangulationLinearFamily("(0,9,~8)(~0,22,7)(1,8,2)(~1,~19,~7)(~2,~3,~11)(3,11,~10)(4,~14,15)(~4,16,~12)(5,~15,12)(~5,~23,18)(6,~16,13)(~6,~17,~20)(~9,10,14)(~13,23,21)(17,20,~18)(19,~22,~21)", "BBRBRBRRRRRRRRBRBBRRRBRR", [(1, phi, 0, 0, 0, 1, 0, 0, -phi, -phi - 1, 0, 0, -phi, -phi, phi + 1, -phi - 1, phi, 0, 0, -phi, 0, phi - 1, -1, -1), (0, 0, 1, 0, 0, 0, phi - 1, 0, 1, 1, 1, 1, 0, phi - 1, 0, 0, 0, 0, phi - 1, 0, phi - 1, 0, 0, phi - 1), (0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, phi - 1, 0, 0, -phi + 1, 0, 0, 0), (0, 0, 0, 0, 1, 0, 0, phi - 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, phi - 1, 0, 0, phi - 1, 0)])
            sage: f.stratum()  # optional - surface_dynamics
            Q_4(11, 1)
            sage: f.dimension()
            4
            sage: f.rank()
            2
        """
        from sage.rings.rational_field import QQ
        from sage.rings.number_field.number_field import NumberField
        from sage.rings.qqbar import AA

        x = QQ['x'].gen()

        fp = "(0,9,~8)(1,8,2)(10,14,~9)(3,11,~10)(~2,~3,~11)(~14,15,4)(12,5,~15)(~4,16,~12)(13,6,~16)(23,21,~13)(18,~5,~23)(17,20,~18)(~6,~17,~20)(~0,22,7)(~21,19,~22)(~7,~1,~19)"
        cols = "BBRBRBRRRRRRRRBRBBRRRBRR"
        vt = VeeringTriangulation(fp, cols)
        K = NumberField(x**2 - x - 1, 'phi', embedding=(AA(5).sqrt() + 1)/2)
        phi = K.gen()
        L = LinearExpressions(K)
        cs = ConstraintSystem(24)
        vt._set_switch_conditions(cs.insert, [L.variable(e) for e in range(24)])
        cs.insert(L.variable(1) == phi * L.variable(0))
        cs.insert(L.variable(3) == phi * L.variable(17))
        cs.insert(L.variable(2) == phi * L.variable(6))
        cs.insert(L.variable(4) == phi * L.variable(7))
        return VeeringTriangulationLinearFamily(vt, cs.linear_generators_matrix())

    @staticmethod
    def quadrilateral_1_1_1_7_unfolding_orbit_closure():
        r"""
        EXAMPLES::

            sage: from veerer.linear_family import VeeringTriangulationLinearFamilies
            sage: f = VeeringTriangulationLinearFamilies.quadrilateral_1_1_1_7_unfolding_orbit_closure()
            sage: f
            VeeringTriangulationLinearFamily("(0,~14,~18)(~0,~20,13)(1,8,20)(~1,6,~2)(2,19,5)(3,~5,~6)(~3,16,~17)(4,7,~10)(~4,17,~19)(~7,~8,~9)(9,~11,~13)(10,14,~12)(11,15,~16)(12,~15,18)", "RBRBBRRRRBRRRBBBBRRBR", [(1, 0, phi - 1, 0, 0, phi - 1, phi - 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1), (0, 1, 0, 0, 0, -1, -1, phi - 1, 0, -phi + 1, phi - 1, phi, 0, 1, phi - 1, phi - 1, -1, 1, -phi + 1, 1, 1), (0, 0, 0, 1, 0, -1, 0, phi, phi, 0, phi, phi, phi, phi, 0, phi, 0, 1, 0, 1, phi), (0, 0, 0, 0, 1, 0, 0, -phi, -1, phi - 1, -phi + 1, -phi, -phi + 1, -1, 0, -phi + 1, 1, -1, 0, 0, -1)])
            sage: f.stratum()  # optional - surface_dynamics
            H_4(6)
            sage: f.base_ring()
            Number Field in phi with defining polynomial x^2 - x - 1 with phi = 1.618033988749895?
            sage: f.dimension()
            4
            sage: f.rank()
            2
        """
        from sage.rings.number_field.number_field import NumberField
        from sage.rings.polynomial.polynomial_ring_constructor import PolynomialRing
        from sage.rings.qqbar import AA
        fp = "(0,~14,~18)(~0,~20,13)(1,8,20)(~1,6,~2)(2,19,5)(3,~5,~6)(~3,16,~17)(4,7,~10)(~4,17,~19)(~7,~8,~9)(9,~11,~13)(10,14,~12)(11,15,~16)(12,~15,18)"
        cols = "RBRBBRRRRBRRRBBBBRRBR"
        vt = VeeringTriangulation(fp, cols)
        R = PolynomialRing(QQ, 'x')
        x = R.gen()
        K = NumberField(x**2 - x - 1, 'phi', embedding=(1 + AA(5).sqrt()) / 2)
        phi = K.gen()
        L = LinearExpressions(K)
        cs = ConstraintSystem(21)
        vt._set_switch_conditions(cs.insert, [L.variable(e) for e in range(21)])
        cs.insert(L.variable(0) == phi * L.variable(2))
        cs.insert(L.variable(1) == phi * L.variable(14))
        cs.insert(L.variable(16) == phi * L.variable(9))
        cs.insert(L.variable(11) == phi * L.variable(17))
        return VeeringTriangulationLinearFamily(vt, cs.linear_generators_matrix())

    @staticmethod
    def quadrilateral_1_1_1_9_unfolding_orbit_closure():
        r"""
        EXAMPLES::

            sage: from veerer.linear_family import VeeringTriangulationLinearFamilies
            sage: f = VeeringTriangulationLinearFamilies.quadrilateral_1_1_1_9_unfolding_orbit_closure()
            sage: f
            VeeringTriangulationLinearFamily("(0,7,4)(~0,14,13)(1,10,~7)(~1,5,9)(2,~11,~12)(~2,11,6)(3,~8,~5)(~3,~4,~6)(8,~10,12)", "RBRRBRRRBRBBRBR", [(1, 0, 0, 0, -1/2, 0, 1/2, 1/2, 0, 0, -1/2, -1/2, 1/2, -1, 0), (0, 1, 0, 0, 0, -1, 0, 0, 1, 0, 1, 0, 0, 0, 0), (0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 2), (0, 0, 0, 1, 1, 2, 0, 1, -1, 2, -1, 0, 0, 0, 0)])
            sage: f.stratum()  # optional - surface_dynamics
            Q_1(1^3, -1^3)
            sage: f.base_ring()
            Rational Field
            sage: f.dimension()
            4
            sage: f.rank()
            2
        """
        fp = "(0,7,4)(~0,14,13)(1,10,~7)(~1,5,9)(2,~11,~12)(~2,11,6)(3,~8,~5)(~3,~4,~6)(8,~10,12)"
        cols = "RBRRBRRRBRBBRBR"
        vt = VeeringTriangulation(fp, cols)
        L = LinearExpressions(QQ)
        cs = ConstraintSystem(15)
        vt._set_switch_conditions(cs.insert, [L.variable(e) for e in range(15)])
        cs.insert(L.variable(0) == 2 * L.variable(6))
        cs.insert(L.variable(14) == 2 * L.variable(2))
        return VeeringTriangulationLinearFamily(vt, cs.linear_generators_matrix())

    @staticmethod
    def quadrilateral_1_1_2_8_unfolding_orbit_closure():
        r"""
        EXAMPLES::

            sage: from veerer.linear_family import VeeringTriangulationLinearFamilies
            sage: f = VeeringTriangulationLinearFamilies.quadrilateral_1_1_2_8_unfolding_orbit_closure()
            sage: f
            VeeringTriangulationLinearFamily("(0,4,~6)(~0,11,5)(1,~9,10)(~1,7,~3)(2,~7,6)(3,~10,~8)(~4,8,~12)(~5,9,12)", "RRRBRBBRRRBRB", [(1, 0, 0, 0, 1, 1, 0, 0, 1, -1, -1, 2, 0), (0, 1, 0, 0, 1, 2, 1, 1, 2, -1, -2, 2, 1), (0, 0, 1, 0, -1, -2, -1, 0, -3/2, 3/2, 3/2, -2, -1/2), (0, 0, 0, 1, 1, 2, 1, 1, 2, -1, -1, 2, 1)])
            sage: f.stratum()  # optional - surface_dynamics
            Q_2(6, -1^2)
            sage: f.base_ring()
            Rational Field
            sage: f.dimension()
            4
            sage: f.rank()
            2
        """
        fp = "(0,4,~6)(~0,11,5)(1,~9,10)(~1,7,~3)(2,~7,6)(3,~10,~8)(~4,8,~12)(~5,9,12)"
        cols = "RRRBRBBRRRBRB"
        vt = VeeringTriangulation(fp, cols)
        L = LinearExpressions(QQ)
        cs = ConstraintSystem(13)
        vt._set_switch_conditions(cs.insert, [L.variable(e) for e in range(13)])
        cs.insert(L.variable(11) == 2 * L.variable(4))
        return VeeringTriangulationLinearFamily(vt, cs.linear_generators_matrix())

    @staticmethod
    def quadrilateral_1_1_2_12_unfolding_orbit_closure():
        r"""
        EXAMPLES::

            sage: from veerer.linear_family import VeeringTriangulationLinearFamilies
            sage: f = VeeringTriangulationLinearFamilies.quadrilateral_1_1_2_12_unfolding_orbit_closure()
            sage: f
            VeeringTriangulationLinearFamily("(0,~6,~14)(1,~4,15)(~1,4,~2)(2,12,~3)(3,17,8)(5,~7,9)(~5,~12,~8)(6,~10,16)(7,~13,10)(~9,18,~11)(11,13,19)(14,~18,~15)", "BBRBRRRBRBRBBRBRBRRR", [(1, 0, 0, 1/2*sqrt2, 0, 0, -1, 0, -1/2*sqrt2, 0, 0, 0, 1/2*sqrt2, 0, 0, 0, 1, -sqrt2, 0, 0), (0, 1, 0, 0, -1, 0, 0, sqrt2 + 1, 0, sqrt2 + 1, 0, sqrt2 + 1, 0, -sqrt2 - 1, 0, 0, 0, 0, 0, 0), (0, 0, 1, 0, 1, 0, -1/2*sqrt2, -1/2*sqrt2 - 1, -1, -1/2*sqrt2 - 1, 1/2*sqrt2, 0, 1, sqrt2 + 1, -1/2*sqrt2, 1, sqrt2, -1, 1/2*sqrt2 + 1, sqrt2 + 1), (0, 0, 0, 0, 0, 1, 1/2*sqrt2, 1/2*sqrt2 + 1, 1, 1/2*sqrt2, 1/2*sqrt2, 0, 0, -1, 1/2*sqrt2, 0, 0, 1, -1/2*sqrt2, -1)])
            sage: f.stratum()  # optional - surface_dynamics
            Q_1(1^4, -1^4)
            sage: f.base_ring()
            Number Field in sqrt2 with defining polynomial x^2 - 2 with sqrt2 = 1.414213562373095?
            sage: f.dimension()
            4
            sage: f.rank()
            2
        """
        from sage.rings.number_field.number_field import NumberField
        from sage.rings.polynomial.polynomial_ring_constructor import PolynomialRing
        from sage.rings.qqbar import AA
        fp = "(0,~6,~14)(1,~4,15)(~1,4,~2)(2,12,~3)(3,17,8)(5,~7,9)(~5,~12,~8)(6,~10,16)(7,~13,10)(~9,18,~11)(11,13,19)(14,~18,~15)"
        cols = "BBRBRRRBRBRBBRBRBRRR"
        vt = VeeringTriangulation(fp, cols)
        R = PolynomialRing(QQ, 'x')
        x = R.gen()
        K = NumberField(x**2 - 2, 'sqrt2', embedding=AA(2).sqrt())
        sqrt2 = K.gen()
        L = LinearExpressions(K)
        cs = ConstraintSystem(20)
        vt._set_switch_conditions(cs.insert, [L.variable(e) for e in range(20)])
        cs.insert(L.variable(0) == sqrt2 * L.variable(3))
        cs.insert(L.variable(1) == (sqrt2 - 1) * L.variable(11))
        cs.insert(L.variable(17) == sqrt2 * L.variable(6))
        cs.insert(L.variable(16) == sqrt2 * L.variable(12))
        return VeeringTriangulationLinearFamily(vt, cs.linear_generators_matrix())

    @staticmethod
    def quadrilateral_1_2_2_11_unfolding_orbit_closure():
        r"""
        EXAMPLES::

            sage: from veerer.linear_family import VeeringTriangulationLinearFamilies
            sage: f = VeeringTriangulationLinearFamilies.quadrilateral_1_2_2_11_unfolding_orbit_closure()
            sage: f
            VeeringTriangulationLinearFamily("(0,~17,~6)(~0,~3,4)(1,7,18)(~1,12,3)(2,13,~14)(~2,10,9)(5,~9,~16)(~5,6,~7)(8,11,14)(~10,~13,15)(~11,16,17)", "RBBBRBRRBRBRRRRBRBB", [(1, 0, 0, 0, 1, 1/2*sqrt2, -1/2*sqrt2, 0, 1, 0, 0, -1, 0, 0, 0, 0, 1/2*sqrt2, 1/2*sqrt2 + 1, 0), (0, 1, 0, 0, 0, 1/2*sqrt2, -1/2*sqrt2 - 1, -1, 1, -1/2*sqrt2, 1/2*sqrt2, -1/2*sqrt2 - 1, -1, -1/2*sqrt2, -1/2*sqrt2, 0, 0, 1/2*sqrt2 + 1, 0), (0, 0, 1, 0, 0, -1, sqrt2 + 1, sqrt2, -sqrt2, 1, 0, sqrt2 + 1, 0, 0, 1, 0, 0, -sqrt2 - 1, sqrt2), (0, 0, 0, 1, -1, 0, 0, 0, sqrt2, -1/2*sqrt2, 1/2*sqrt2, -1/2*sqrt2, 1, 1/2*sqrt2, 1/2*sqrt2, sqrt2, -1/2*sqrt2, 0, 0)])
            sage: f.stratum()  # optional - surface_dynamics
            Q_2(9, -1^5)
            sage: f.base_ring()
            Number Field in sqrt2 with defining polynomial x^2 - 2 with sqrt2 = 1.414213562373095?
            sage: f.dimension()
            4
            sage: f.rank()
            2
        """
        from sage.rings.number_field.number_field import NumberField
        from sage.rings.polynomial.polynomial_ring_constructor import PolynomialRing
        from sage.rings.qqbar import AA
        fp = "(0,~17,~6)(~0,~3,4)(1,7,18)(~1,12,3)(2,13,~14)(~2,10,9)(5,~9,~16)(~5,6,~7)(8,11,14)(~10,~13,15)(~11,16,17)"
        cols = "RBBBRBRRBRBRRRRBRBB"
        vt = VeeringTriangulation(fp, cols)
        R = PolynomialRing(QQ, 'x')
        x = R.gen()
        K = NumberField(x**2 - 2, 'sqrt2', embedding=AA(2).sqrt())
        sqrt2 = K.gen()
        L = LinearExpressions(K)
        cs = ConstraintSystem(19)
        vt._set_switch_conditions(cs.insert, [L.variable(e) for e in range(19)])
        cs.insert(L.variable(18) == sqrt2 * L.variable(2))
        cs.insert(L.variable(15) == sqrt2 * L.variable(3))
        cs.insert(L.variable(4) == sqrt2 * L.variable(16))
        cs.insert(L.variable(5) == (sqrt2 - 1) * L.variable(17))
        return VeeringTriangulationLinearFamily(vt, cs.linear_generators_matrix())

    @staticmethod
    def quadrilateral_1_2_2_15_unfolding_orbit_closure():
        r"""
        EXAMPLES::

            sage: from veerer.linear_family import VeeringTriangulationLinearFamilies
            sage: f = VeeringTriangulationLinearFamilies.quadrilateral_1_2_2_15_unfolding_orbit_closure()
            sage: f
            VeeringTriangulationLinearFamily("(0,11,9)(~0,5,20)(1,~11,17)(~1,4,~3)(2,18,~7)(~2,16,7)(3,12,~20)(~4,~16,6)(~5,~18,~13)(~6,~14,22)(8,19,~12)(~8,10,~21)(~9,21,~15)(~10,14,~17)(13,15,~19)", "RBBBRBRRBBRRRRRBBBBRBRB", [(1, 0, 0, 0, 0, 2, phi - 1, phi - 1, -1, phi - 1, 1, phi, 1, phi + 1, phi + 1, phi - 1, -phi + 1, phi, -phi + 1, 2, 1, 0, 2), (0, 1, 0, 0, -1, 0, -1, 0, 0, phi - 1, -phi + 1, phi - 1, 0, 0, 1, 0, 0, phi, 0, 0, 0, -phi + 1, 2), (0, 0, 1, 0, 0, phi, 0, 1, 0, 0, 0, 0, phi, phi, 0, 0, 0, 0, 0, phi, phi, 0, 0), (0, 0, 0, 1, 1, -phi + 1, 0, -1, phi - 1, 0, 0, 0, -phi, -phi, 0, phi - 1, 1, 0, 1, -2*phi + 1, -phi + 1, phi - 1, 0)])
            sage: f.stratum()  # optional - surface_dynamics
            Q_2(1^5, -1)
            sage: f.base_ring()
            Number Field in phi with defining polynomial x^2 - x - 1 with phi = 1.618033988749895?
            sage: f.dimension()
            4
            sage: f.rank()
            2
        """
        from sage.rings.number_field.number_field import NumberField
        from sage.rings.polynomial.polynomial_ring_constructor import PolynomialRing
        from sage.rings.qqbar import AA
        fp = "(0,11,9)(~0,5,20)(1,~11,17)(~1,4,~3)(2,18,~7)(~2,16,7)(3,12,~20)(~4,~16,6)(~5,~18,~13)(~6,~14,22)(8,19,~12)(~8,10,~21)(~9,21,~15)(~10,14,~17)(13,15,~19)"
        cols = "RBBBRBRRBBRRRRRBBBBRBRB"
        vt = VeeringTriangulation(fp, cols)
        R = PolynomialRing(QQ, 'x')
        x = R.gen()
        K = NumberField(x**2 - x - 1, 'phi', embedding=(1 + AA(5).sqrt()) / 2)
        phi = K.gen()
        L = LinearExpressions(K)
        cs = ConstraintSystem(23)
        vt._set_switch_conditions(cs.insert, [L.variable(e) for e in range(23)])
        cs.insert(L.variable(4) == phi * L.variable(21))
        cs.insert(L.variable(7) == (phi - 1) * L.variable(12))
        cs.insert(L.variable(9) == (2 - phi) * L.variable(17))
        cs.insert(L.variable(11) == (phi - 1) * L.variable(14))
        return VeeringTriangulationLinearFamily(vt, cs.linear_generators_matrix())
